version: "3.7"

services: 
    redis:
        container_name: redis
        image: redis:latest
        ports: 
            - "6379:6379"
        restart: unless-stopped
        environment: 
            - REDIS_PASSWORD=password
        volumes: 
            - ~/DockerData/Redis:/data

    redisinsight:
        container_name: redisinsight
        image: redislabs/redisinsight:latest
        restart: unless-stopped
        ports:
            - '8001:8001'
        volumes:
            - ~/DockerData/RedisInsight:/db

    redis-commander:
        container_name: redis-commander
        image: rediscommander/redis-commander
        restart: unless-stopped
        ports: 
            - "8081:8081"
        environment: 
            - REDIS_HOST=redis
            - REDIS_PASSWORD=password
            - REDIS_PORT=6379
    
    mongo:
        container_name: mongo
        image: mongo:4.4
        ports:
            - "27017:27017"
        restart: unless-stopped
        volumes: 
            - ~/DockerData/Mongo/db:/data/db

    nats:
        container_name: nats
        image: nats:latest
        restart: unless-stopped
        ports: 
            - "4222:4222"
            - "8222:8222"

    nats-webui:
        container_name: nats-webui
        image: sphqxe/nats-webui:latest
        restart: unless-stopped
        ports: 
            - "8082:80"