version: "3.7"

services: 
    redis:
        container_name: redis
        image: redis:latest
        ports: 
            - "6379:6379"
        restart: unless-stopped
        volumes: 
            - ~/DockerData/Redis:/data

    redisinsight:
        container_name: redisinsight
        image: redislabs/redisinsight:latest
        restart: unless-stopped
        ports:
            - '8002:8001'
        volumes:
            - ~/DockerData/RedisInsight:/db

    redis-commander:
        container_name: redis-commander
        image: rediscommander/redis-commander
        restart: unless-stopped
        ports: 
            - "8081:8081"
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    
    mongo:
        container_name: mongo
        image: mongo:4.4
        ports:
            - "27017:27017"
        restart: unless-stopped
        volumes: 
            - ~/DockerData/Mongo/db:/data/db

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        restart: unless-stopped
        ports: 
            - "5672:5672"
            - "15672:15672"
            - "15692:15692"
            - "25672:25672"
        volumes:
            - ~/DockerData/rabbitmq:/var/lib/rabbitmq
            - ~/DockerData/rabbitmq/log/:/var/log/rabbitmq