global:
  scrape_interval:     30s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: central-api
    metrics_path: /apimetrics
    static_configs:
      - targets: ['host.docker.internal:49557']

  - job_name: central-services
    metrics_path: /servicemetrics
    file_sd_configs:
      - files:
          - targets.json
        refresh_interval: 10s